# Generated by Django 2.1.5 on 2019-02-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190215_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('name', 'ticker')},
        ),
    ]
